// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpyxgwzqzprkydymsmna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhweXhnd3pxenBya3lkeW1zbW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzU4ODgsImV4cCI6MjA2MzgxMTg4OH0.1SAW2PCrqI-p3icw2Poc8JP2muqP-BVC8-GGd8i1Lgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);